# trigger on release branch
name: Release Workflow
on:
  push:
    branches:
      - release

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            
            - id: checkout
              uses: actions/checkout@v3
              with:
                sparse-checkout: |
                  .github
                  extension
            - id: setup-key
              env:
                  PRIVATE_KEY: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}
              run: |
                  echo "$PRIVATE_KEY" >> key.pem
                  chmod 400 key.pem
            # pack zip and read manifest, can be reused in the following steps
            - id: packExtensionDir
              uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
              with:
                extensionDir: 'extension'
                zipFilePath: 'build/extension.zip'

            - id: createCrx
              uses: cardinalby/webext-buildtools-chrome-crx-action@v2
              with:
                # zip file made at the packExtensionDir step
                zipFilePath: 'build/extension.zip'
                crxFilePath: 'build/extension.crx'
                privateKey: key.pem
    